POSITIVE_FRAMING_PHRASES = {
    # Phrases that shift from negative to positive or offer alternatives
    "what i can do is": "Offers an alternative, focusing on solutions.",
    "let's see what we can do": "Collaborative and solution-oriented.",
    "here's what we can do": "Directly states possible actions.",
    "an alternative would be": "Suggests other options.",
    "one option is": "Presents a choice.",
    "i can certainly try to": "Shows effort, even if outcome is uncertain.",
    "let me find out for you": "Proactive in seeking information.",
    "i'd be happy to look into that": "Positive and willing tone.",
    "we can explore": "Suggests looking for solutions together.",
    "while [negative outcome], we can [positive action]": "Contrasts a limitation with a helpful action.",
    "although [limitation], perhaps we could": "Acknowledges constraint but seeks solution.",
    "i recommend we": "Shows confidence in proposed solution.",
    "a good approach would be": "Presents solution with confidence.",
    "i can immediately": "Shows readiness for prompt action.",
    "here's how we'll solve this": "Confident solution framing.",
    "i'm going to take care of this by": "Takes ownership of resolution.",
    "what's most effective is": "Presents optimal solution strategy.",
    "the best way forward is": "Provides clear direction."
}

SOLUTION_ORIENTED_KEYWORDS = [
    "solution",
    "alternative",
    "option",
    "resolve",
    "fix",
    "address",
    "help you with",
    "work towards",
    "figure out",
    "investigate",
    "explore",
    "see what's possible",
    "find a way",
    "solve",
    "implement",
    "next steps",
    "action plan",
    "remedy",
    "approach",
    "strategy",
    "resolve",
    "prioritize",
    "expedite",
    "facilitate",
    "coordinate"
] 